# The Docker image that will be used to build your app
image: node
# Functions that should be executed before the build script is run
before_script:
  - cd ./front/ui
  - CI=false npm install
  - rm -rf build
pages:
  script:
    - CI=false npm run build
    - cp build/index.html build/404.html
    - ls
    - cd ..
    - cd ..
    - mkdir public
    - ls
    - mv ./front/ui/build/* public
    - export
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
